// <auto-generated />
using System;
using GimnasioFinal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GimnasioFinal.Migrations
{
    [DbContext(typeof(GimnasioContext))]
    [Migration("20251209210703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GimnasioFinal.Models.Clase", b =>
                {
                    b.Property<int>("IdClase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreClase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdClase");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("GimnasioFinal.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GimnasioFinal.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoMembresia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("GimnasioFinal.Models.Reservacion", b =>
                {
                    b.Property<int>("IdReservacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaReservacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdClase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdReservacion");

                    b.HasIndex("IdClase");

                    b.HasIndex("IdCliente");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("GimnasioFinal.Models.Pago", b =>
                {
                    b.HasOne("GimnasioFinal.Models.Cliente", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GimnasioFinal.Models.Reservacion", b =>
                {
                    b.HasOne("GimnasioFinal.Models.Clase", "Clase")
                        .WithMany("Reservaciones")
                        .HasForeignKey("IdClase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GimnasioFinal.Models.Cliente", "Cliente")
                        .WithMany("Reservaciones")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GimnasioFinal.Models.Clase", b =>
                {
                    b.Navigation("Reservaciones");
                });

            modelBuilder.Entity("GimnasioFinal.Models.Cliente", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Reservaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
